language: node_js
node_js:
  - "11"
dist: trusty
sudo: required
branches:
  only:
    - dev
before_script:
  - npm install -g @angular/cli
script:
  - ng test
  - ng build --dev --base-href https://semyonic.github.io/commerce-cart-app/
