version: '3.7'

services:
  dev.web:
    container_name: commerce-app-dev
    image: semyonic/commerce-app:latest
    build:
      context: .
      args:
        env: dev
    ports:
      - "80:9999"
  test.web:
    container_name: commerce-app-test
    image: semyonic/commerce-app:latest
    build:
      context: .
      args:
        env: test
    ports:
      - "80:9999"
  prod.web:
    container_name: commerce-app-prod
    image: semyonic/commerce-app:latest
    build:
      context: .
      args:
        env: prod
    ports:
      - "80:9999"
